<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="smoke-test-suite" duration-ms="19818" started-at="2015-02-25T04:00:47Z" finished-at="2015-02-25T04:01:07Z">
    <groups>
    </groups>
    <test name="BairdSauceFailTest" duration-ms="19107" started-at="2015-02-25T04:00:47Z" finished-at="2015-02-25T04:01:07Z">
      <class name="com.booj.sauce.sauce_framework.BairdSauceFailTest">
        <test-method status="PASS" signature="setupTest(java.lang.reflect.Method)[pri:0, instance:com.booj.sauce.sauce_framework.BairdSauceFailTest@6a024a67]" name="setupTest" is-config="true" duration-ms="10606" started-at="2015-02-24T21:00:47Z" finished-at="2015-02-24T21:00:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.booj.sauce.sauce_framework.BairdSauceFailTest.test_Account_Login_Page_Appear_Correct_Fail() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="FAIL" signature="test_Account_Login_Page_Appear_Correct_Fail()[pri:0, instance:com.booj.sauce.sauce_framework.BairdSauceFailTest@6a024a67]" name="test_Account_Login_Page_Appear_Correct_Fail" duration-ms="3921" started-at="2015-02-24T21:00:58Z" finished-at="2015-02-24T21:01:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.booj.sauce.sauce_framework.BairdSauceFailTest.test_Account_Login_Page_Appear_Correct_Fail(BairdSauceFailTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Account_Login_Page_Appear_Correct_Fail -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.booj.sauce.sauce_framework.BairdSauceFailTest@6a024a67]" name="tearDown" is-config="true" duration-ms="198" started-at="2015-02-24T21:01:06Z" finished-at="2015-02-24T21:01:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.booj.sauce.sauce_framework.BairdSauceFailTest -->
    </test> <!-- BairdSauceFailTest -->
    <test name="BairdSaucePassTest" duration-ms="19818" started-at="2015-02-25T04:00:47Z" finished-at="2015-02-25T04:01:07Z">
      <class name="com.booj.sauce.sauce_framework.BairdSaucePassTest">
        <test-method status="PASS" signature="setupTest(java.lang.reflect.Method)[pri:0, instance:com.booj.sauce.sauce_framework.BairdSaucePassTest@67b6d4ae]" name="setupTest" is-config="true" duration-ms="14089" started-at="2015-02-24T21:00:47Z" finished-at="2015-02-24T21:01:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.booj.sauce.sauce_framework.BairdSaucePassTest.test_Account_Login_Page_Appear_Correct_Pass() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="test_Account_Login_Page_Appear_Correct_Pass()[pri:0, instance:com.booj.sauce.sauce_framework.BairdSaucePassTest@67b6d4ae]" name="test_Account_Login_Page_Appear_Correct_Pass" duration-ms="5206" started-at="2015-02-24T21:01:02Z" finished-at="2015-02-24T21:01:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Account_Login_Page_Appear_Correct_Pass -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.booj.sauce.sauce_framework.BairdSaucePassTest@67b6d4ae]" name="tearDown" is-config="true" duration-ms="244" started-at="2015-02-24T21:01:07Z" finished-at="2015-02-24T21:01:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.booj.sauce.sauce_framework.BairdSaucePassTest -->
    </test> <!-- BairdSaucePassTest -->
  </suite> <!-- smoke-test-suite -->
</testng-results>
